In [1]:
import numpy as np
import numa as nm

In [5]:
H = (1/4) * np.array(
    [
        [0, 1, 1, 0],
        [1, 0, 0, 1],
        [1, 0, 0, 1],
        [0, 1, 1, 0]
    ]
)

g = (1/4)*np.array([1, 2, 0, 1])

nm.primitive_iterative_systems_method(H, g)

                                             x(i)                 err
0                           [0.25 0.5  0.   0.25]  0.2500000000000000
1                       [0.375 0.625 0.125 0.375]  0.1250000000000000
2                   [0.4375 0.6875 0.1875 0.4375]  0.0625000000000000
3               [0.46875 0.71875 0.21875 0.46875]  0.0312500000000000
4           [0.484375 0.734375 0.234375 0.484375]  0.0156250000000000
5       [0.4921875 0.7421875 0.2421875 0.4921875]  0.0078125000000000
6   [0.49609375 0.74609375 0.24609375 0.49609375]  0.0039062500000000
7   [0.49804688 0.74804688 0.24804688 0.49804688]  0.0019531250000000
8   [0.49902344 0.74902344 0.24902344 0.49902344]  0.0009765625000000
9   [0.49951172 0.74951172 0.24951172 0.49951172]  0.0004882812500000
10  [0.49975586 0.74975586 0.24975586 0.49975586]  0.0002441406250000
11  [0.49987793 0.74987793 0.24987793 0.49987793]  0.0001220703125000
12  [0.49993896 0.74993896 0.24993896 0.49993896]  0.0000610351562500
13  [0.49996948 0.74

In [13]:
A = np.array(
    [
        [4, -1, 2],
        [2, 5, 1],
        [1, 1, -3]
    ]
)
 
b = np.array([-12, 5, -4])

nm.jaccobi_systems_method(A, b)

[[ 0.          0.25       -0.5       ]
 [-0.4         0.         -0.2       ]
 [ 0.33333333  0.33333333  0.        ]]

[-3.          1.          1.33333333]

                                     x(i)                 err
0   [-3.          1.          1.33333333]  3.0000000000000000
1   [-3.41666667  1.93333333  0.66666667]  0.4166666666666665
2   [-2.85        2.23333333  0.83888889]  0.5666666666666664
3   [-2.86111111  1.97222222  1.12777778]  0.0111111111111111
4   [-3.07083333  1.91888889  1.03703704]  0.2097222222222221
5   [-3.0387963   2.02092593  0.94935185]  0.0320370370370369
6   [-2.96944444  2.02564815  0.99404321]  0.0693518518518519
7   [-2.99060957  1.98896914  1.01873457]  0.0211651234567900
8   [-3.012125    1.99249691  0.99945319]  0.0215154320987656
9   [-3.00160237  2.00495936  0.9934573 ]  0.0105226337448561
10  [-2.99548881  2.00194949  1.001119  ]  0.0061135545267490
11  [-3.00007213  1.99797172  1.00215356]  0.0045833161865567
12  [-3.00158385  1.99959814  0.9992

In [5]:
nm.gauss_seidl_systems_method(A, b)

[[ 0.          0.25       -0.5       ]
 [ 0.         -0.1         0.        ]
 [ 0.          0.05       -0.16666667]]

[-3.          2.2         1.06666667]

                                     x(i)                 err
0   [-3.          2.2         1.06666667]  3.0000000000000000
1   [-2.98333333  1.98        0.99888889]  0.0166666666666666
2   [-3.00444444  2.002       0.99918519]  0.0211111111111109
3   [-2.99909259  1.9998      1.0002358 ]  0.0053518518518518
4      [-3.0001679  2.00002    0.9999507]  0.0010753086419757
5   [-2.99997035  1.999998    1.00000922]  0.0001975514403294
6   [-3.00000511  2.0000002   0.99999836]  0.0000347585733880
7   [-2.99999913  1.99999998  1.00000028]  0.0000059764288980
8   [-3.00000015  2.          0.99999995]  0.0000010144048166
9   [-2.99999998  2.          1.00000001]  0.0000001709008028
10                          [-3.  2.  1.]  0.0000000286668005
11                          [-3.  2.  1.]  0.0000000047961333
12                          [-3.  2.

In [14]:
A = np.array(
    [
        [-7, 2, -1, 2],
        [2, -7, 2, -1],
        [-1, 2, -7, 2],
        [2, -1, 2, -7]
    ]
)
 
b = np.array([17, 14, -1, -34])

In [15]:
nm.jaccobi_systems_method(A, b)

[[ 0.          0.28571429 -0.14285714  0.28571429]
 [ 0.28571429  0.          0.28571429 -0.14285714]
 [-0.14285714  0.28571429  0.          0.28571429]
 [ 0.28571429 -0.14285714  0.28571429  0.        ]]

[-2.42857143 -2.          0.14285714  4.85714286]

                                                 x(i)                 err
0   [-2.42857143 -2.          0.14285714  4.85714286]  2.4285714285714284
1   [-1.63265306 -3.34693878  1.30612245  4.48979592]  0.7959183673469385
2   [-2.28862974 -2.73469388  0.70262391  5.24198251]  0.6559766763848396
3   [-1.81257809 -3.20199917  1.18617243  4.79466889]  0.4760516451478551
4   [-2.14297614 -2.86392575  0.85684536  5.13559826]  0.3303980484322011
5   [-1.90192862 -3.10112283  1.09804588  4.89880917]  0.2410475227158755
6   [-2.07181046 -2.92951066  0.9281859   5.07047962]  0.1698818398067861
7   [-1.949464   -3.05110411  1.05053548  4.94889451]  0.1223464608752320
8   [-2.0364221  -2.96382165  0.96357783  5.03617815]  0.0869581001767692
9  

In [16]:
nm.gauss_seidl_systems_method(A, b)

[[ 0.          0.28571429 -0.14285714  0.28571429]
 [ 0.          0.08163265  0.24489796 -0.06122449]
 [ 0.         -0.01749271  0.09037901  0.22740525]
 [ 0.          0.06497293 -0.04997918  0.15535194]]

[-2.42857143 -2.69387755 -0.27988338  4.46813828]

                                                 x(i)                 err
0   [-2.42857143 -2.69387755 -0.27988338  4.46813828]  2.4285714285714284
1   [-1.88165645 -3.25588828  0.75802235  5.00123144]  0.5469149759028977
2   [-2.03819086 -3.08022407  0.98288652  4.99565934]  0.1565344084359053
3   [-2.02171657 -3.01047421  0.99886955  4.9949686 ]  0.0164742941360942
4   [-2.00426868 -3.00082384  0.99893689  4.99859432]  0.0174478856699909
5   [-2.00048513 -3.00024154  0.99959867  4.99978123]  0.0037835500450152
6   [-2.00007419 -3.00010461  0.9999182   4.99997038]  0.0004109461849775
7   [-2.00002667 -3.00002676  0.9999877   4.99999269]  0.0000475184990858
8   [-2.00000798 -3.00000475  0.99999769  4.99999774]  0.0000186898305454
9  